---
title: "Regression and Correlation"
author: "GilbertQ"
date: "`r Sys.Date()`"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
    encoding = encoding,
    output_file = file.path(dirname(input_file), out_dir, 'index.html'))})
---  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is the content of the 10th chapter of the book:

```{r employees}
employees<-read.csv("hfda_ch10_employees.csv", header=TRUE)
head(employees,n=10)
```

Here is the Summary:

```{r thesumm}
summary(employees)
```

## Including Plots

and here is the Plot for the employees that negotiatied:

```{r theplot}
plot(employees$requested[employees$negotiated==TRUE],employees$received[employees$negotiated==TRUE])
```

And the Correlation factor:

```{r thecor}
cor(employees$requested[employees$negotiated==TRUE],employees$received[employees$negotiated==TRUE])
```
Finally, here is the trend line:
```{r theline}
library(ggplot2)
data <- data.frame(x = employees$requested[employees$negotiated==TRUE], y = employees$received[employees$negotiated==TRUE])
ggplot(data, aes(x = x, y = y)) +
  geom_point() +  # Add scatterplot points
  geom_smooth(method = "lm", col = "blue") +  # Add linear trend line
  ggtitle("Scatterplot with Trend Line") +
  xlab("X-axis") +
  ylab("Y-axis")
```